#!/usr/bin/env node
import { Command } from "commander";
import { login } from "./commands/login.js";
import { init } from "./commands/init.js";
import { openWalkthru } from "./commands/open.js";
import { newCommit } from "./commands/new-commit.js";
import { runCommitGate } from "./hooks/commit.js";

const program = new Command();

program
  .name("walkthru")
  .description("Comprehension gate for git commits")
  .version("0.1.0")
  .action(openWalkthru);

program
  .command("open")
  .description("Open the local Walkthru menu")
  .action(openWalkthru);

program
  .command("login")
  .description("Authenticate with GitHub")
  .action(login);

program
  .command("init")
  .description("Install the Walkthru commit hook in the current repo")
  .action(init);

program
  .command("new-commit <commit-description...>")
  .description("Register an upcoming commit with Walkthru")
  .option("--message <commit-subject>", "Commit subject/title generated by the agent")
  .option("--commit-id <correlation-id>", "Caller-provided correlation id for the upcoming commit")
  .action(newCommit);

const hook = program.command("hook").description("Internal hook runners (called by git)");

hook
  .command("commit-msg <msg-file>")
  .description("Run the comprehension gate")
  .action(runCommitGate);

program.parse();
