#!/usr/bin/env node
import { Command } from "commander";
import { login } from "./commands/login.js";
import { init } from "./commands/init.js";
import { openWalkthru } from "./commands/open.js";
import { newCommit } from "./commands/new-commit.js";
import { runPostCommitHook, runPrePushHook } from "./hooks/commit.js";

const program = new Command();

program
  .name("walkthru")
  .description("Register commits with Walkthru")
  .version("0.1.0")
  .action(openWalkthru);

program
  .command("open")
  .description("Open the Walkthru web app dashboard")
  .action(openWalkthru);

program
  .command("login")
  .description("Authenticate with GitHub")
  .action(login);

program
  .command("init")
  .description("Install Walkthru git hooks in the current repo")
  .action(init);

program
  .command("new-commit <commit-description...>")
  .description("Register an upcoming commit with Walkthru")
  .option("--message <commit-subject>", "Commit subject/title generated by the agent")
  .option("--commit-id <correlation-id>", "Caller-provided correlation id for the upcoming commit")
  .action(newCommit);

const hook = program.command("hook").description("Internal hook runners (called by git)");

hook
  .command("post-commit")
  .description("Register the commit that was just created")
  .action(runPostCommitHook);

hook
  .command("pre-push")
  .description("Register outgoing commits that were not registered locally")
  .action(runPrePushHook);

program.parse();
